
samples: data/processed/sanger/samples.txt

identify_insertions:
    reference: data/interim/references/imfusion/GRCm38.76.t2onc.tophat
    options:
    threads: 6

quantify_expression:
    exon_gtf: data/external/ensembl/Mus_musculus.GRCm38.76.DEXSeq.gtf
    options:
        - --paired
        - --stranded 2

call_ctgs:
    reference: data/interim/references/imfusion/GRCm38.76.t2onc.tophat
    chromosomes: 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X
    pattern: 'TA'
    min_depth: 10
    threshold: 0.05
    exon_gtf: data/external/ensembl/Mus_musculus.GRCm38.76.DEXSeq.gtf
    de_threshold: 1.0
    options:
        - --window 20000 20000
