
samples: data/processed/sb/samples.txt

identify_insertions:
    reference: data/interim/references/imfusion/GRCm38.76.t2onc.star
    options:
    threads: 1

quantify_expression:
    exon_gtf: data/external/ensembl/Mus_musculus.GRCm38.76.DEXSeq.gtf
    options:

call_ctgs:
    reference: data/interim/references/imfusion/GRCm38.76.t2onc.star
    chromosomes: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X
    pattern: 'TA'
    min_depth: 2
    threshold: 0.05
    exon_gtf: data/external/ensembl/Mus_musculus.GRCm38.76.DEXSeq.gtf
    de_threshold: 1.0
    options:
        - --window 20000 20000
